version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=fireAlarm
      - MYSQL_USER=mo
      - MYSQL_PASSWORD=mo
      - MYSQL_ROOT_PASSWORD=root
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5050:5050"
    depends_on:
      - mysql
    restart: on-failure

  client:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 5173:5173
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true